const { botname, emoji, ownername, mode, devname, prefix, cpyear } = require('./setup');
const bloom = require('../package.json');

module.exports = {
    about: `_Hi, I am ${botname} ${emoji}_\n> A WhatsApp multidevice AI written in JavaScrip based on Baileys. I was developed by Master ${ownername} and LICENSED under ISC licensing policy at ColdNode Labs (Naivasha, Kenya), I am one of the most current advanced Artificial Intelligence user-bot model with more than 400 features and functionalities, you can check other productions from my developer on GitHub (${devname}). You can contact dev ${devname} by opening a ticket here: \n${emoji} To open a ticket send: *(${prefix}ticket)*`,
    ticket: `┌───── 🎫 Ticket Created ─────\n├ ${devname} will be back to you shortly\n├ Check (${prefix}menu) for commands\n└─────────────────`,
    bloom: `┌────${emoji} ${botname} ─────\n├   > Version: ${bloom.version} beta\n├   > Global prefix: ${prefix}\n├    _A reason to imagine_\n├    _Operating mode: ${mode}_\n└─────────────────\n> (c) ${cpyear} ${botname} By @${devname} - ☁️ •|•`,
    powered: `┌──── Powered By ────\n└─ ${devname}`,
    admin: `┌──── ⚠️ Notice ────\n└─ This command is meant for group admins only!`,
    owner: `┌──── ⚠️ Notice ────\n└─ This Command is meant for ${botname} owner only!`,
    autorestart: `┌──── 🔄 Auto Restart ────\n├ ${botname} Will restart automatically\n└─ to apply changes`,
    manualrestart: `┌──── 🔄 Manual Restart ────\n├ Please restart ${botname} manually\n└─ to apply changes`,
    norestart: `┌──── ⚠️ Access Denied ────\n└─ Only ${botname} owner can restart bot`,
    shut: `┌──── 🔌 Shutdown ────\n└─ Shutting down.... Manual restart required!`,
    noshut: `┌──── ⚠️ Access Denied ────\n└─ Unauthorized`,
    ping: `┌──── 📡 Latency ────\n└─ Response time:`,
    search: `┌──── 🔍 Searching ────\n└─ Please wait for results...`,
    nosearch: `┌──── ❌ No Results ────\n└─ No matching content found`,
    broadcast: `┌──── 📢 Broadcast ────\n└─ Message sent successfully`,
    restarting: `┌────────────────────\n├> *🔁 Restarting ${emoji} ${botname}....*\n├ _I will notify you once I\'m online_\n├ Restart manually in case I fail.\n└────────────────────── 🚀`,
    group: `┌──── ⚠️ Notice ────\n└─ This command can only be used in group chats.`,
    agenda: `┌──── 🔒 Private Access ────\n└─ This is a private agenda for ${botname} owner only`,
    ticketarg: `┌──── 🎫 Ticket Usage ────\n├ Please write your issue or ticket ID\n├ Examples:\n├ !ticket something is not ok with this...\n└─ !ticket BB-0000A`,
    noarg: `┌──── ⚠️ Incomplete Command ────\n└─ Please provide required arguments`,
    limited: `┌──── ⚠️ Limit Notice ────\n└─ You can only have up to 3 open tickets at a time`,
    gmetafail: `┌──── ❌ Error ────\n└─ Failed to fetch group metadata`,
    botadmin: `┌──── ⚠️ Admin Required ────\n├ ${botname} needs to be admin first!\n└─ Cannot perform that action`,
    youadmin: `┌──── ⚠️ Access Denied ────\n├ You are not an admin!\n└─ You can't use that command`,
    wenot: `┌──── ❌ Admin Status ────\n└─ Neither I nor you are admins in this group.`,
    nsfwoff: `┌──── 🔞 NSFW Status ────\n├ NSFW is not enabled in this group\n└─ To enable use *${prefix}nsfw on*`,
    nsfwon: `┌──── 🔞 NSFW Status ────\n├ NSFW is already enabled in this group\n└─ To disable use *${prefix}nsfw off*`,
    games: `┌──── 🎮 Games Status ────\n├ Games are not enabled in this group\n└─ To enable use *${prefix}act games*`,
    economy: `┌──── 💰 Economy Status ────\n├ Economy is not enabled in this group\n└─ To enable use *${prefix}act economy*`,
    act: `┌──── ⚙️ Activation Help ────\n├ A second parameter is required!\n└─ Usage: ${prefix}act (economy,games,nsfw,welcome,left)`,
    deact: `┌──── ⚙️ Deactivation Help ────\n├ A second parameter is required!\n└─ Usage: ${prefix}deact (economy,games,nsfw,welcome,left)`,
    add: `┌──── 👥 Add User Help ────\n├ To add a user in this group:\n└─ Usage: ${prefix}add 2547xxxxxxxx`,
    joinlink: `┌──── 🔗 Join Group Help ────\n├ I need a group link or group code\n└─ Usage: ${prefix}join your_valid_group_link_or_code_here`,
    error404: `┌──── ❌ Command Error ────\n├ Command not found in database\n└─ Try ${prefix}menu to view available commands`,
    error: `┌──── ❌ Error ────\n└─ An error occurred! I will notify the Developer`,
    bug: `┌──── 🐛 Bug Report ────\n├ An error occurred!\n└─ I have sent a report to bot developer(s)`,
    not_a_repo: `┌──── ❌ Git Error ────\n└─ This folder is not a Git repository.`,
    no_updates: `┌──── ✅ Update Status ────\n└─ Already up to date!`,
    pull_success: `┌──── ✅ Git Status ────\n└─ Pulled latest changes successfully!`,
    pull_failed: `┌──── ❌ Git Error ────\n└─ Git pull failed!`,
    restart_later: `┌──── ⏰ Restart Status ────\n└─ Restart cancelled. You can restart manually later.`,
    restarting_now: `┌──── ♻️ Restart Status ────\n└─ Restarting the bot now...`,
    restart_failed: `┌──── ❌ Restart Error ────\n└─ Restart failed!`,
    installing_dependencies: `┌──── 📦 Installation ────\n└─ Installing dependencies...`,
    install_failed: `┌──── ❌ Install Error ────\n└─ Failed to install dependencies!`,
    privateMode: `┌──── 🔒 Private Mode ────\n└─ Bot set to private for now, please do not disturb`,
    blocked: `┌──── ⛔ Privacy Notice ────\n└─ You will be blocked for violating privacy policy`,
    groupOnly: `┌──── 👥 Group Mode ────\n└─ Bot have been set to group only`,
    footer: `> (c) ${cpyear} ${botname} By @${devname} - ☁️ •|•`
};